_wandb:
    value:
        cli_version: 0.24.0
        e:
            dra1coyvxyrieyyoci3zs90g9gp7r55j:
                args:
                    - --test-mode
                codePath: hyperparameter_sweep_optuna.py
                codePathLocal: hyperparameter_sweep_optuna.py
                cpu_count: 8
                cpu_count_logical: 12
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "1023099793408"
                        used: "733415923712"
                email: compte.tmrl@gmail.com
                executable: C:\Users\felix\OneDrive\Documents\Data Mining\.venv\Scripts\python.exe
                git:
                    commit: 78c1121c54f014b040a48baad12a21e39bf478ac
                    remote: https://github.com/Fane-Nathan/TMRL-Test.git
                gpu: NVIDIA GeForce GTX 1650
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 896
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce GTX 1650
                      uuid: GPU-6c2ed864-a983-393e-0b0b-88585f527827
                host: FelixNathaniel
                memory:
                    total: "25459941376"
                os: Windows-10-10.0.26200-SP0
                program: C:\Users\felix\OneDrive\Documents\Data Mining\tmrl\hyperparameter_sweep_optuna.py
                python: CPython 3.11.9
                root: C:\Users\felix\OneDrive\Documents\Data Mining\tmrl
                startedAt: "2026-02-12T05:02:21.069061Z"
                writerId: dra1coyvxyrieyyoci3zs90g9gp7r55j
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 35
                - 105
            "2":
                - 1
                - 35
                - 105
            "3":
                - 2
                - 13
                - 16
            "4": 3.11.9
            "5": 0.24.0
            "8":
                - 3
            "10":
                - 20
            "12": 0.24.0
            "13": windows-amd64
hyperparameters:
    value:
        alpha: 0.2979221734836258
        alpha_floor: 0.1459476894296684
        batch_size: 256
        betas_actor_str: 0.95,0.999
        betas_critic_str: 0.95,0.999
        gamma: 0.9792970989617431
        l2_actor: 9.462175356461487e-06
        l2_critic: 1.4656553886225336e-05
        lr_actor: 0.00012399967836846095
        lr_critic: 2.3426581058204037e-05
        lr_entropy: 0.008105016126411584
        polyak: 0.998296868115208
        redq_m: 1
        redq_n: 8
        target_entropy: -0.6512526460895272
max_epochs:
    value: 3
test_mode:
    value: true
trial_number:
    value: 2
