_wandb:
    value:
        cli_version: 0.24.0
        e:
            2r4f5h5ajsd54bga9egofpubghra87wp:
                args:
                    - --test-mode
                codePath: hyperparameter_sweep_optuna.py
                codePathLocal: hyperparameter_sweep_optuna.py
                email: compte.tmrl@gmail.com
                executable: C:\Users\felix\OneDrive\Documents\Data Mining\.venv\Scripts\python.exe
                git:
                    commit: 78c1121c54f014b040a48baad12a21e39bf478ac
                    remote: https://github.com/Fane-Nathan/TMRL-Test.git
                host: FelixNathaniel
                os: Windows-10-10.0.26200-SP0
                program: C:\Users\felix\OneDrive\Documents\Data Mining\tmrl\hyperparameter_sweep_optuna.py
                python: CPython 3.11.9
                root: C:\Users\felix\OneDrive\Documents\Data Mining\tmrl
                startedAt: "2026-02-12T04:52:11.851893Z"
                writerId: 2r4f5h5ajsd54bga9egofpubghra87wp
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 35
                - 105
            "2":
                - 1
                - 35
                - 105
            "3":
                - 2
                - 13
                - 16
            "4": 3.11.9
            "5": 0.24.0
            "8":
                - 3
            "10":
                - 20
            "12": 0.24.0
            "13": windows-amd64
hyperparameters:
    value:
        alpha: 0.1633820882890881
        alpha_floor: 0.011492999300221412
        batch_size: 512
        betas_actor:
            - 0.95
            - 0.999
        betas_critic:
            - 0.95
            - 0.999
        gamma: 0.9797696977431705
        l2_actor: 0.0002661901888489054
        l2_critic: 8.200518402245835e-06
        lr_actor: 8.168455894760161e-05
        lr_critic: 0.00037183641805732076
        lr_entropy: 3.972110727381908e-05
        polyak: 0.9915347171131856
        redq_m: 2
        redq_n: 2
        target_entropy: -1.5189635778448938
max_epochs:
    value: 3
test_mode:
    value: true
trial_number:
    value: 1
