_wandb:
    value:
        cli_version: 0.24.0
        e:
            6bnb4e6zf5359mld3dpkb2yo59zrjod3:
                args:
                    - --test-mode
                codePath: hyperparameter_sweep_optuna.py
                codePathLocal: hyperparameter_sweep_optuna.py
                email: compte.tmrl@gmail.com
                executable: C:\Users\felix\OneDrive\Documents\Data Mining\.venv\Scripts\python.exe
                git:
                    commit: 78c1121c54f014b040a48baad12a21e39bf478ac
                    remote: https://github.com/Fane-Nathan/TMRL-Test.git
                host: FelixNathaniel
                os: Windows-10-10.0.26200-SP0
                program: C:\Users\felix\OneDrive\Documents\Data Mining\tmrl\hyperparameter_sweep_optuna.py
                python: CPython 3.11.9
                root: C:\Users\felix\OneDrive\Documents\Data Mining\tmrl
                startedAt: "2026-02-12T05:02:29.073233Z"
                writerId: 6bnb4e6zf5359mld3dpkb2yo59zrjod3
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 35
                - 105
            "2":
                - 1
                - 35
                - 105
            "3":
                - 2
                - 13
                - 16
            "4": 3.11.9
            "5": 0.24.0
            "8":
                - 3
            "10":
                - 20
            "12": 0.24.0
            "13": windows-amd64
hyperparameters:
    value:
        alpha: 0.2679027504615932
        alpha_floor: 0.012483440997339655
        batch_size: 128
        betas_actor_str: 0.95,0.999
        betas_critic_str: 0.9,0.999
        gamma: 0.9675648206986693
        l2_actor: 1.5512259126484753e-06
        l2_critic: 8.569331925053988e-06
        lr_actor: 1.0257563974185649e-05
        lr_critic: 0.0004274869455295214
        lr_entropy: 0.001319994226153501
        polyak: 0.9910428215357262
        redq_m: 1
        redq_n: 4
        target_entropy: -1.0718241332851357
max_epochs:
    value: 3
test_mode:
    value: true
trial_number:
    value: 3
